In [5]:
# Matrix generator with saddle point
import numpy as np
import numpy.random as rnd

def make_matrix(n, m):
    matr = np.zeros((n, m))

    c = rnd.randint(2, 20)
    print("Clear sum:", c, "\n")

    row = rnd.randint(n)
    column = rnd.randint(m)

    matr[row][column] = c
    for i in range(0, m):
        if matr[row][i] == 0:
            matr[row][i] = rnd.randint(c, 20)
    for i in range(0, n):
        if matr[i][column] == 0:
            matr[i][column] = rnd.randint(1, c)
    for i in range(0, n):
        for j in range(0, m):
            if matr[i][j] == 0:
                matr[i][j] = rnd.randint(1, 20)

    print("The matrix:")
    print(matr, "\n")

    def get_max_min(matr):
        lst = []
        for i in matr:
            lst.append(min(i))
        return(max(lst))

    def get_min_max(matr):  
        lst = []
        for i in range(0, m):
            lst.append(max(matr[ :, i]))
        return(min(lst))

    print("Max min = ", get_max_min(matr))
    print("Min max = ", get_min_max(matr))
    
for i in range(0, 5):
    n = rnd.randint(2, 10)
    m = rnd.randint(2, 10)
    print("Matrix ", n, "x", m)
    make_matrix(n, m)
    print("_____________________________")

Matrix  4 x 4
Clear sum: 17 

The matrix:
[[ 7.  9.  6.  6.]
 [11. 17. 12. 17.]
 [16. 13. 12. 12.]
 [17. 19. 17. 18.]] 

Max min =  17.0
Min max =  17.0
_____________________________
Matrix  2 x 2
Clear sum: 17 

The matrix:
[[ 7.  9.]
 [18. 17.]] 

Max min =  17.0
Min max =  17.0
_____________________________
Matrix  8 x 6
Clear sum: 6 

The matrix:
[[15.  8.  2. 18. 12.  8.]
 [16.  9.  2.  1. 13. 14.]
 [15. 15.  6. 18.  6. 12.]
 [ 6.  2.  3.  5. 17. 15.]
 [19. 16.  3. 12. 10.  8.]
 [ 8. 19.  3. 14.  5.  2.]
 [14.  5.  2.  6.  5. 17.]
 [11.  8.  2. 14. 15.  8.]] 

Max min =  6.0
Min max =  6.0
_____________________________
Matrix  9 x 6
Clear sum: 15 

The matrix:
[[13. 16. 18.  7.  6.  8.]
 [ 7. 19. 12.  2.  3.  4.]
 [16.  6. 10.  3.  2.  1.]
 [16. 17. 17. 15. 16. 16.]
 [ 8.  4.  6.  5.  3. 14.]
 [ 7.  5.  7.  1.  4.  7.]
 [ 7. 13. 17. 14. 19. 17.]
 [ 2.  1. 11.  2.  2.  6.]
 [ 9. 18. 18. 12.  9. 19.]] 

Max min =  15.0
Min max =  15.0
_____________________________
Matrix  3 x 5
Clea